name: "web_app"
mode: "dev"
port: 8080
version: "v0.2"

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 8086
  user: "root"
  password: "1127"
  dbname: "camps_user"
  max_open_conns: 30
  max_idle_conns: 10

redis:
  host: "127.0.0.1"
  port: 8089
  db: 0
  pool_size: 10
  password: ""